"""Minimal implementation of autograd"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_micrograd.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_micrograd.ipynb 2
import numpy as np
import matplotlib.pyplot as plt
from fastcore.utils import L

# %% ../nbs/01_micrograd.ipynb 4
print("Hello")
