"""Some utilities to visualize graph"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_utils.ipynb.

# %% auto 0
__all__ = ['trace', 'draw_dot']

# %% ../nbs/02_utils.ipynb 2
import numpy as np
import matplotlib.pyplot as plt
from fastcore.utils import L
import pathlib
import os

# %% ../nbs/02_utils.ipynb 5
from fastcore.utils import store_attr, basic_repr

# %% ../nbs/02_utils.ipynb 18
def trace(root):
    nodes, edges = set(), set()
    def build(v):
        if v: nodes.add(v)
        for child in v._prev:
            edges.add((child, v))
            build(child)
    build(root)
    return nodes, edges

# %% ../nbs/02_utils.ipynb 27
import graphviz
from graphviz import Digraph

# %% ../nbs/02_utils.ipynb 28
def draw_dot(root):
    dot = Digraph(format="svg", graph_attr={"rankdir":'LR'})
    nodes, edges = trace(root)
    for n in nodes:
        # print(str(id(n)))
        uid = str(id(n))
        dot.node(uid, label=f" {{ {n.label}|{n.data:.4f}| grad: {n.grad:.4f}  }}", shape='record') # For { in f-string use {{
        if n._op:
            dot.node(uid+n._op, n._op)
            dot.edge(uid+n._op, uid)
    for n1, n2 in edges:
        dot.edge(str(id(n1)), str(id(n2))+n2._op)
        
    return dot

# %% ../nbs/02_utils.ipynb 53
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='IPython.core.formatters')
